"""
********* Euler Problem 2 *********
PROMPT:
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

"""

## Brute coding approach

# Set up variables
fib1 = 1
fib2 = 2
total = 0

# Determine fibonnaci numbers and sum even ones
while fib2 < 4e6:
    if fib2 % 2 == 0: # if even:
        total += fib2 # add to total count

    fib3 = fib1 + fib2 # calculate the next fib 
    
    # reassign the previous two fibs to move on
    fib1 = fib2 
    fib2 = fib3

print(total)
     